pipeline {
    environment {
        IMAGEN = "ybpytt"
        USUARIO = 'USER_DOCKERHUB'
    }
    agent none
    stages {
        stage('Clone') {
            agent any
            steps {
                sh 'docker version'
                git branch: "main", url: 'https://github.com/yoskiburgosmatrix/ytt.git'
            }
        }
         
        stage('Build') {
            agent any
            steps {
                script {
                    newApp = docker.build "$IMAGEN:$BUILD_NUMBER"
                    // newApp = docker.build "debian"
                }
            }
        }

        /* 
        stage('Test') {
            steps {
                script {
                    docker.image("$IMAGEN:$BUILD_NUMBER").inside('-u root') {
                           sh 'apache2ctl -v'
                        }
                    }
            }
        }
        
      stage('Deploy') {
            steps {
                script {
                    docker.withRegistry( '', USUARIO ) {
                        newApp.push()
                    }
                }
            }
        }
        stage('Clean Up') {
            steps {
                sh "docker rmi $IMAGEN:$BUILD_NUMBER"
                }
        }
        */
    }
}