## This file restrictict the project to allow only selected destinaion
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-01
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: despliegue01
    server: https://kubernetes.default.svc
  project: project-01
  source:
    path: despliegue01
    repoURL: https://bitbucket.agile.bns/scm/dsope/poc_ytt.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
