## This file contains default project config of the project creation
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
 name: project-01
 namespace: argocd
spec:
 description: Project 4 description
 sourceRepos:
  - "*"
 destinations:
  - server: "*"
    namespace: "*"
 clusterResourceWhitelist:
  - group: "*"
    kind: "*"
 namespaceResourceWhitelist:
  - group: "*"
    kind: "*"  
