apiVersion: apps/v1
kind: Deployment
metadata:
  name:  despliegue01
  namespace: despliegue01
  labels:
    app:  despliegue01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: despliegue01
  template:
    metadata:
      labels:
        app:  despliegue01
    spec:
      containers:
      - name: hola-aws101
        image: dolguin/hola-aws101:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080